### ISSUE TITLE
Rack and Sinatra gems have been updated

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/cloudfoundry-conjur-demo#26]
Upgrade the following gems to resolve security warnings in the repository: 

- Rack >= 2.0.6
- Sinatra >= 2.0.2

These vulnerabilities impact a demo application, not core functionality.

**Comment by izgeri** [comment]
```
gem 'rack', ">= 2.0.6"
gem 'sinatra', ">= 2.0.2"
```

**Comment by izgeri** [comment]
@micahlee can you address this with the demo fixes you are making?

**Comment by micahlee** [comment]
@izgeri sure thing!

**Comment by micahlee** [comment]
This is addressed in #23
